name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build and publish
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
        # poetry version $(git describe --tags --abbrev=0)
