name: Publish to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build and publish
        run: |
          export VERSION=$(git describe --tags --abbrev=0)
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml

          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}

      - uses: tiangolo/latest-changes@0.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: "CHANGELOG.md"
          latest_changes_header: "# Release Notes"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: true
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
